# -*- coding: utf-8 -*-
"""RL Fall detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enM1shZ9V1r2UahcwBptY83YgwX7-vs_
"""

import cv2
import numpy as np
from ultralytics import YOLO
import random
pose_model = YOLO("yolov8n-pose.pt")
actions = [0, 1]  # 0 = normal, 1 = fall

q_table = np.zeros((10, 2))  # states × actions

alpha = 0.1
gamma = 0.9
epsilon = 0.1
def get_state(keypoints):

    shoulder = keypoints[5]
    hip = keypoints[11]

    dx = shoulder[0] - hip[0]
    dy = shoulder[1] - hip[1]

    angle = abs(np.degrees(np.arctan2(dy, dx)))

    state = int(angle // 18)  # 0-9 buckets

    return min(state, 9), angle
    def choose_action(state):

    if random.uniform(0,1) < epsilon:
        return random.choice(actions)

    return np.argmax(q_table[state])
    def get_reward(angle, action):

    if angle < 30 and action == 1:
        return 10   # correct fall detection

    if angle >= 30 and action == 0:
        return 2    # correct normal posture

    return -5       # wrong decision
    cap = cv2.VideoCapture(0)

prev_state = 0

while True:

    ret, frame = cap.read()

    if not ret:
        break

    results = pose_model(frame)

    annotated = results[0].plot()

    if len(results[0].keypoints) > 0:

        keypoints = results[0].keypoints.xy[0].cpu().numpy()

        state, angle = get_state(keypoints)

        action = choose_action(state)

        reward = get_reward(angle, action)

        next_state = state

        q_table[state, action] = q_table[state, action] + alpha * (
            reward + gamma * np.max(q_table[next_state]) - q_table[state, action]
        )

        if action == 1:
            cv2.putText(
                annotated,
                "FALL DETECTED",
                (40,60),
                cv2.FONT_HERSHEY_SIMPLEX,
                1.2,
                (0,0,255),
                3
            )
            print("⚠ FALL DETECTED")



    cv2.imshow("RL Fall Detection", annotated)

    if cv2.waitKey(1) & 0xFF == 27:
        break

cap.release()
cv2.destroyAllWindows()